language: java

jdk:
  - oraclejdk11
  - openjdk11

cache:
  directories:
    - $HOME/.m2

script: 
  - mvn install -DskipTests
  - mvn mvn dependency:go-offline

before_install:
  - chmod +x build.sh

after_success:
  - mvn integration-test